provider "aws" {
  region = "___________" # Enter Your desired region e.g us-east-1
  access_key = "_____________________" ## Enter your access_key eg. AH.............
  secret_key = "_____________________" ## Enter Your Secret_key eg. zOfQBF6lI/Z7...............
}
