name: SSH NFS Setup
on:
  workflow_call:
    inputs:
        VOL_NAME:
          required: true
          type: string
        NETAPP_IP:
          required: true
          type: string
        DIR_NAME:          # That You want to create inside NetApp Volume
           required: true
           type: string

    secrets:
        GCP_VM_1_IP:
         required: true
        GCP_USER:
         required: true
        GCP_SSH_KEY:
          required: true
        GCP_VM_2_IP:
            required: true

env:
  VOL_NAME: ${{inputs.VOL_NAME}}
  NETAPP_IP: ${{inputs.NETAPP_IP}}
  DIR_NAME: ${{inputs.DIR_NAME}}


jobs:
  setup-nfs-vm1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
    # Installing NFS PACKAGE
      - name: Install NFS common package on GCP VM 1
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_1_IP}}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y nfs-common
            sudo mkdir -p ${{ env.VOL_NAME}} 
            sudo mount -t nfs -o nolock,rw,hard,rsize=65536,wsize=65536,vers=3,tcp ${{ env.NETAPP_IP}}:${{ env.VOL_NAME}} ${{ env.VOL_NAME}} 
            df -h | grep ${{ env.VOL_NAME}}  
            ls -ld ${{ env.VOL_NAME}} 
            sudo chmod 755 ${{ env.VOL_NAME}} 
            sudo mkdir -p ${{ env.VOL_NAME}}/${{ env.DIR_NAME}}
            sudo ls -la ${{ env.VOL_NAME}} 

# We need to set up this in another vm, so that we can verify that the directory or folder that we are making in instance 1 Is easily accessible inside the net app volume in instance 2
  setup-nfs-vm2:
    runs-on: ubuntu-latest
    needs: setup-nfs-vm1
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    # Installing NFS PACKAGE
      - name: Install NFS common package on GCP VM 2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_2_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y nfs-common
            sudo mkdir -p ${{ env.VOL_NAME}} 
            sudo mount -t nfs -o nolock,rw,hard,rsize=65536,wsize=65536,vers=3,tcp ${{ env.NETAPP_IP}}:${{ env.VOL_NAME}} ${{ env.VOL_NAME}} 
            df -h | grep ${{ env.VOL_NAME}} 
            ls -ld ${{ env.VOL_NAME}} 
            sudo chmod 755 ${{ env.VOL_NAME}} 
            sudo ls -la ${{ env.VOL_NAME}}       