name: SSH NFS Setup
on:
  push:
    branches:
      - GCP

jobs:
  setup-nfs-vm1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install NFS common package on GCP VM 1
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_1_IP}}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            sudo su - 
            sudo apt-get update
            sudo apt-get install -y nfs-common
            sudo mkdir -p /vol1
            sudo mount -t nfs -o nolock,rw,hard,rsize=65536,wsize=65536,vers=3,tcp 10.29.0.4:/vol1 /vol1
            df -h 
            ls -ld /vol1
            sudo mkdir testt

  setup-nfs-vm2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install NFS common package on GCP VM 2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_2_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            sudo su - 
            sudo apt-get update
            sudo apt-get install -y nfs-common
            sudo mkdir -p /vol1
            sudo mount -t nfs -o nolock,rw,hard,rsize=65536,wsize=65536,vers=3,tcp 10.29.0.4:/vol1 /vol1
            df -h 
            ls -ld /vol1
            ls -la 